# Generated by Django 5.1.1 on 2024-10-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Caja', 'Venta en Caja'), ('Cuenta', 'Venta en Cuenta')], default='Caja', max_length=6, verbose_name='Tipo de Venta'),
        ),
    ]
