# Generated by Django 5.1.2 on 2024-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_venta_tipo_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cambio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='dinero_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero recibido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total de la venta'),
        ),
    ]
