# Generated by Django 5.1.2 on 2024-10-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_venta_cambio_alter_venta_dinero_recibido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
        migrations.AlterModelTable(
            name='cuenta',
            table='Cuenta',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
