# Generated by Django 5.1.1 on 2024-10-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cuenta_options_alter_cuenta_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='fecha_cuenta',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-16 00:00:00', verbose_name='Fecha cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='fecha_detalle',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-16 00:00:00', verbose_name='Fecha detalle'),
            preserve_default=False,
        ),
    ]
